from collections import namedtuple

Achievement = namedtuple(
    'Achievement', ['achievement', 'description', 'link'])
achievements = [
    Achievement('Implemented van Emde Boas Tree',
                '1st time correct implementation in python in the History',
                'https://github.com/pctablet505/van-Emde-Boas-Tree'),
    Achievement('World Programming Championship - IIT Mumbai',
                'Rank 69 | Certificate no 99695',
                ''),
    Achievement('Gold in HackFest 2020',
                '''Rank 29 | 8051  Rating 2042.08 from 1500''',
                'https://www.hackerrank.com/results/hackerrank-hackfest-2020/pctablet505'),
    Achievement('GATE 2021',
                '''Got AIR 5648''',
                '/static/gate2021.png'),
    Achievement('CodeVita Season 9',
                '''Cleared Round 1 with Rank 1042''',
                ''),
    Achievement('CodeVita Season 9',
                '''Got International 242 in Round 2''',
                ''),
    Achievement('CodeVita Season 10',
                '''Got International 426 in Round 1''',
                ''),
    Achievement('Hack the Interview III',
                '''Rank(73 | 919)''',
                'https://www.hackerrank.com/results/hack-the-interview-iv/pctablet505'),
    Achievement('Hack the Interview IV (Asia Pacific)',
                '''Rank(100 | 4353)''',
                'https://www.hackerrank.com/results/hack-the-interview-iv-apac/pctablet505'),
    Achievement('Hack the Interview IV (U.S.) ',
                '''Rank( 65 | 1217) ''',
                'https://www.hackerrank.com/results/hack-the-interview-iv/pctablet505?h_r=profile'),
    Achievement('Hackerrank Algorithms',
                '''Rank 1026/ 2219538''',
                'https://www.hackerrank.com/leaderboard?filter=pctablet505&filter_on=hacker&page=1&track=algorithms&type=practice'),
    Achievement('Hackerrank Data Structures ',
                '''Rank 540| 931788''',
                'https://www.hackerrank.com/leaderboard?filter=pctablet505&filter_on=hacker&page=1&track=data-structures&type=practice'),
    Achievement('Hackerrank Python Practice',
                '''Rank 1''',
                'https://www.hackerrank.com/leaderboard?filter=pctablet505&filter_on=hacker&page=1&track=python&type=practice'),
]
