from collections import namedtuple

Certificate = namedtuple('Certificate', ['credential', 'src', 'title'])

certificates = [
    Certificate(credential='https://courses.edx.org/certificates/8cbde197f6874661ab8794d753f9fd7b',
                src='static/certificates/MIT Machine Learning.png', title='MIT Machine Learning with Python-From Linear Models to Deep Learning'),
    Certificate(credential='https://cs50.harvard.edu/certificates/2b1773c1-473d-4a7b-89ae-460d23154126',
                src='static/certificates/CS50 AI.png', title='CS50 Introduction to Artificial Intelligence with Python'),
    Certificate(credential='https://www.coursera.org/account/accomplishments/certificate/UA73U5EJC6XJ',
                src='static/certificates/IBM Introductioin to AI.png', title='IBM Introductioin to AI'),
    Certificate(credential='http://ude.my/UC-d7c52c49-464f-4b63-a9b4-2da5d4c53ff4/',
                src='static/certificates/Machine Learning.jpg', title='Udemy Complete 2020 Data Science & Machine Learning Bootcamp'),
    Certificate(credential='https://www.hackerrank.com/certificates/58d066424a1e',
                src='static/certificates/C Advanced.png', title='C Advanced'),
    Certificate(credential='https://www.hackerrank.com/certificates/0c61249bbe1d',
                src='static/certificates/C Basic.png', title='C Basic'),
    Certificate(credential='https://www.hackerrank.com/certificates/337182b9dc84',
                src='static/certificates/C Intermediate.png', title='C Intermediate'),
    Certificate(credential='https://www.hackerrank.com/certificates/92d056e955d2',
                src='static/certificates/CSS.png', title='CSS'),
    Certificate(credential='https://www.hackerrank.com/certificates/253bacd0f0c0',
                src='static/certificates/Java.png', title='Java'),
    Certificate(credential='https://www.kaggle.com/learn/certification/pctablet505/intermediate-machine-learning',
                src='static/certificates/Kaggle - Intermediate Machine Learning.png', title='Kaggle Intermediate Machine Learning'),
    Certificate(credential='https://www.kaggle.com/learn/certification/pctablet505/intro-to-deep-learning',
                src='static/certificates/Kaggle - Intro to Deep Learning.png', title='Kaggle Intro to Deep Learning'),
    Certificate(credential='https://www.kaggle.com/learn/certification/pctablet505/intro-to-machine-learning',
                src='static/certificates/Kaggle - Intro to Machine Learning.png', title='Kaggle Intro to Machine Learning'),
    Certificate(credential='https://www.kaggle.com/learn/certification/pctablet505/python',
                src='static/certificates/Kaggle - Python.png', title='Kaggle Python'),
    Certificate(credential='https://www.hackerrank.com/certificates/fc7b9af8aac8',
                src='static/certificates/problem Solving Advanced.png', title='Problem Solving Advanced'),
    Certificate(credential='https://www.hackerrank.com/certificates/e3c6568f71c6',
                src='static/certificates/Problem Solving Basic.png', title='Problem Solving Basic'),
    Certificate(credential='https://www.hackerrank.com/certificates/f5bcd6aa9355',
                src='static/certificates/Problem Solving Intermediate.png', title='Problem Solving Intermediate'),
    Certificate(credential='https://www.hackerrank.com/certificates/6e9c190da189',
                src='static/certificates/Python Advanced.png', title='Python Advanced'),
    Certificate(credential='https://www.hackerrank.com/certificates/93d10484c124',
                src='static/certificates/Python Basic.png', title='Python Basic'),
    Certificate(credential='https://www.hackerrank.com/certificates/9ecfb2a355a2',
                src='static/certificates/Python Intermediate.png', title='Python Intermediate'),
    Certificate(credential='https://www.hackerrank.com/certificates/2508bf1f2b12',
                src='static/certificates/SQL Basic.png', title='SQL Basic'),
    Certificate(credential='https://www.hackerrank.com/certificates/74470a9fe364',
                src='static/certificates/SQL Intermediate.png', title='SQL Intermediate'),
    Certificate(credential='https://www.udemy.com/certificate/UC-37c2faaf-17c4-4089-ab2d-18190a8aa61f/',
                src='static/certificates/DSA.jpg', title='Udemy Data Structures and Algorithms'),
    Certificate(credential='https://www.kaggle.com/learn/certification/pctablet505/intermediate-machine-learning',
                src='static/certificates/Python.jpg', title='Udemy Python'),
]
