from collections import defaultdict

skills = defaultdict(list,
                     {'Advance Data Structures': [],
                      'Algorithms': [],
                      'Artificial Intelligence': ['Search', 'CSP', 'Optimization', 'RL', 'Knowledge Based Agents'],
                      'Statistics': ['Estimation', 'Hypothesis Testing'],
                      'Probability Theory': ['Probabilistic Modeling', 'Inference'],
                      'Machine Learning': ['Clustering',
                                           'Recommendation System',
                                           'Reinforcement Learning',
                                           'Deep Learning',
                                           'TensorFlow',
                                           'PyTorch',
                                           'Scikit-Learn',
                                           'Data visualization'],
                      'Languages': ['Python',
                                    'C',
                                    'C++',
                                    'JavaScript',
                                    ],
                      'Web Programming': ['HTML',
                                          'CSS',
                                          'Flask',
                                          'Django',
                                          'Saas',
                                          'Bootstrap'],
                      'DBMS': ['SQL'],
                      'Arduino': [],
                      'Competitive Programming': [],
                      'Tools': ['Git','heroku','google cloud','jinja'],
                      })
